name: LaTeX PDF Build

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the 'main' branch.
  workflow_dispatch:  # Allows manual triggering of the workflow.

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container:
      image: docker.io/texlive/texlive:latest  # Use a Docker image with a full TeX Live installation.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document to PDF
      run: |
        pdflatex -interaction=nonstopmode proposal.tex 
        biber proposal
        pdflatex -interaction=nonstopmode proposal.tex  
        pdflatex -interaction=nonstopmode proposal.tex  

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: '*.pdf'
